### PR TITLE
Changed the content of collaboration into points

### PR DESCRIPTION
**Pull request by Hardikaz**

### CODE REVIEW

**Review by VaibhavAswal — APPROVED** [review]

**Comment by deepraj02** [comment]
@VaibhavAswal merge mt kr

**Comment by deepraj02** [comment]
@Hardikaz Attatch a screenshot after changes

**Comment by Hardikaz** [comment]
> @Hardikaz Attatch a screenshot after changes

ss of display?

**Comment by deepraj02** [comment]
> > @Hardikaz Attatch a screenshot after changes
> 
> ss of display?

yes

**Comment by Hardikaz** [comment]
WhatsApp Image 2023-02-18 at 8 46 46 PM (1)
WhatsApp Image 2023-02-18 at 8 46 46 PM

**_Uploaded the ss_**

**Comment by deepraj02** [comment]
increase the card width
@Hardikaz

**Comment by deepraj02** [comment]
ss again @Hardikaz

**Pull request merged**
